module.exports = [
  {
    name: 'Afghanistan',
    alphaCode2: 'AF',
    alphaCode3: 'AFG',
    numericCode: '004',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Afghanistan.svg/23px-Flag_of_Afghanistan.svg.png',
  },
  {
    name: 'Åland Islands',
    alphaCode2: 'AX',
    alphaCode3: 'ALA',
    numericCode: '248',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Flag_of_%C3%85land.svg/23px-Flag_of_%C3%85land.svg.png',
  },
  {
    name: 'Albania',
    alphaCode2: 'AL',
    alphaCode3: 'ALB',
    numericCode: '008',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/21px-Flag_of_Albania.svg.png',
  },
  {
    name: 'Algeria',
    alphaCode2: 'DZ',
    alphaCode3: 'DZA',
    numericCode: '012',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/23px-Flag_of_Algeria.svg.png',
  },
  {
    name: 'American Samoa',
    alphaCode2: 'AS',
    alphaCode3: 'ASM',
    numericCode: '016',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Flag_of_American_Samoa.svg/23px-Flag_of_American_Samoa.svg.png',
  },
  {
    name: 'Andorra',
    alphaCode2: 'AD',
    alphaCode3: 'AND',
    numericCode: '020',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/22px-Flag_of_Andorra.svg.png',
  },
  {
    name: 'Angola',
    alphaCode2: 'AO',
    alphaCode3: 'AGO',
    numericCode: '024',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/23px-Flag_of_Angola.svg.png',
  },
  {
    name: 'Anguilla',
    alphaCode2: 'AI',
    alphaCode3: 'AIA',
    numericCode: '660',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/23px-Flag_of_Anguilla.svg.png',
  },
  {
    name: 'Antarctica',
    alphaCode2: 'AQ',
    alphaCode3: 'ATA',
    numericCode: '010',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg/23px-Proposed_flag_of_Antarctica_%28Graham_Bartram%29.svg.png',
  },
  {
    name: 'Antigua and Barbuda',
    alphaCode2: 'AG',
    alphaCode3: 'ATG',
    numericCode: '028',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/23px-Flag_of_Antigua_and_Barbuda.svg.png',
  },
  {
    name: 'Argentina',
    alphaCode2: 'AR',
    alphaCode3: 'ARG',
    numericCode: '032',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/23px-Flag_of_Argentina.svg.png',
  },
  {
    name: 'Armenia',
    alphaCode2: 'AM',
    alphaCode3: 'ARM',
    numericCode: '051',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/23px-Flag_of_Armenia.svg.png',
  },
  {
    name: 'Aruba',
    alphaCode2: 'AW',
    alphaCode3: 'ABW',
    numericCode: '533',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/23px-Flag_of_Aruba.svg.png',
  },
  {
    name: 'Australia',
    alphaCode2: 'AU',
    alphaCode3: 'AUS',
    numericCode: '036',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/23px-Flag_of_Australia_%28converted%29.svg.png',
  },
  {
    name: 'Austria',
    alphaCode2: 'AT',
    alphaCode3: 'AUT',
    numericCode: '040',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/23px-Flag_of_Austria.svg.png',
  },
  {
    name: 'Azerbaijan',
    alphaCode2: 'AZ',
    alphaCode3: 'AZE',
    numericCode: '031',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/23px-Flag_of_Azerbaijan.svg.png',
  },
  {
    name: 'Bahamas',
    alphaCode2: 'BS',
    alphaCode3: 'BHS',
    numericCode: '044',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/23px-Flag_of_the_Bahamas.svg.png',
  },
  {
    name: 'Bahrain',
    alphaCode2: 'BH',
    alphaCode3: 'BHR',
    numericCode: '048',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/23px-Flag_of_Bahrain.svg.png',
  },
  {
    name: 'Bangladesh',
    alphaCode2: 'BD',
    alphaCode3: 'BGD',
    numericCode: '050',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/23px-Flag_of_Bangladesh.svg.png',
  },
  {
    name: 'Barbados',
    alphaCode2: 'BB',
    alphaCode3: 'BRB',
    numericCode: '052',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/23px-Flag_of_Barbados.svg.png',
  },
  {
    name: 'Belarus',
    alphaCode2: 'BY',
    alphaCode3: 'BLR',
    numericCode: '112',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/23px-Flag_of_Belarus.svg.png',
  },
  {
    name: 'Belgium',
    alphaCode2: 'BE',
    alphaCode3: 'BEL',
    numericCode: '056',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/23px-Flag_of_Belgium_%28civil%29.svg.png',
  },
  {
    name: 'Belize',
    alphaCode2: 'BZ',
    alphaCode3: 'BLZ',
    numericCode: '084',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/23px-Flag_of_Belize.svg.png',
  },
  {
    name: 'Benin',
    alphaCode2: 'BJ',
    alphaCode3: 'BEN',
    numericCode: '204',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/23px-Flag_of_Benin.svg.png',
  },
  {
    name: 'Bermuda',
    alphaCode2: 'BM',
    alphaCode3: 'BMU',
    numericCode: '060',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/23px-Flag_of_Bermuda.svg.png',
  },
  {
    name: 'Bhutan',
    alphaCode2: 'BT',
    alphaCode3: 'BTN',
    numericCode: '064',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/23px-Flag_of_Bhutan.svg.png',
  },
  {
    name: 'Bolivia (Plurinational State of)',
    alphaCode2: 'BO',
    alphaCode3: 'BOL',
    numericCode: '068',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/22px-Flag_of_Bolivia.svg.png',
  },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    alphaCode2: 'BQ',
    alphaCode3: 'BES',
    numericCode: '535',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/23px-Flag_of_the_Netherlands.svg.png',
  },
  {
    name: 'Bosnia and Herzegovina',
    alphaCode2: 'BA',
    alphaCode3: 'BIH',
    numericCode: '070',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/23px-Flag_of_Bosnia_and_Herzegovina.svg.png',
  },
  {
    name: 'Botswana',
    alphaCode2: 'BW',
    alphaCode3: 'BWA',
    numericCode: '072',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/23px-Flag_of_Botswana.svg.png',
  },
  {
    name: 'Bouvet Island',
    alphaCode2: 'BV',
    alphaCode3: 'BVT',
    numericCode: '074',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/21px-Flag_of_Norway.svg.png',
  },
  {
    name: 'Brasil',
    alphaCode2: 'BR',
    alphaCode3: 'BRA',
    numericCode: '076',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/22px-Flag_of_Brazil.svg.png',
  },
  {
    name: 'British Indian Ocean Territory',
    alphaCode2: 'IO',
    alphaCode3: 'IOT',
    numericCode: '086',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Flag_of_the_British_Indian_Ocean_Territory.svg/23px-Flag_of_the_British_Indian_Ocean_Territory.svg.png',
  },
  {
    name: 'Brunei Darussalam',
    alphaCode2: 'BN',
    alphaCode3: 'BRN',
    numericCode: '096',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/23px-Flag_of_Brunei.svg.png',
  },
  {
    name: 'Bulgaria',
    alphaCode2: 'BG',
    alphaCode3: 'BGR',
    numericCode: '100',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/23px-Flag_of_Bulgaria.svg.png',
  },
  {
    name: 'Burkina Faso',
    alphaCode2: 'BF',
    alphaCode3: 'BFA',
    numericCode: '854',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/23px-Flag_of_Burkina_Faso.svg.png',
  },
  {
    name: 'Burundi',
    alphaCode2: 'BI',
    alphaCode3: 'BDI',
    numericCode: '108',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/23px-Flag_of_Burundi.svg.png',
  },
  {
    name: 'Cabo Verde',
    alphaCode2: 'CV',
    alphaCode3: 'CPV',
    numericCode: '132',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/23px-Flag_of_Cape_Verde.svg.png',
  },
  {
    name: 'Cambodia',
    alphaCode2: 'KH',
    alphaCode3: 'KHM',
    numericCode: '116',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/23px-Flag_of_Cambodia.svg.png',
  },
  {
    name: 'Cameroon',
    alphaCode2: 'CM',
    alphaCode3: 'CMR',
    numericCode: '120',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/23px-Flag_of_Cameroon.svg.png',
  },
  {
    name: 'Canada',
    alphaCode2: 'CA',
    alphaCode3: 'CAN',
    numericCode: '124',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/23px-Flag_of_Canada_%28Pantone%29.svg.png',
  },
  {
    name: 'Cayman Islands',
    alphaCode2: 'KY',
    alphaCode3: 'CYM',
    numericCode: '136',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/23px-Flag_of_the_Cayman_Islands.svg.png',
  },
  {
    name: 'Central African Republic',
    alphaCode2: 'CF',
    alphaCode3: 'CAF',
    numericCode: '140',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/23px-Flag_of_the_Central_African_Republic.svg.png',
  },
  {
    name: 'Chad',
    alphaCode2: 'TD',
    alphaCode3: 'TCD',
    numericCode: '148',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/23px-Flag_of_Chad.svg.png',
  },
  {
    name: 'Chile',
    alphaCode2: 'CL',
    alphaCode3: 'CHL',
    numericCode: '152',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/23px-Flag_of_Chile.svg.png',
  },
  {
    name: 'China',
    alphaCode2: 'CN',
    alphaCode3: 'CHN',
    numericCode: '156',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png',
  },
  {
    name: 'Christmas Island',
    alphaCode2: 'CX',
    alphaCode3: 'CXR',
    numericCode: '162',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Flag_of_Christmas_Island.svg/23px-Flag_of_Christmas_Island.svg.png',
  },
  {
    name: 'Cocos (Keeling) Islands',
    alphaCode2: 'CC',
    alphaCode3: 'CCK',
    numericCode: '166',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Cocos_%28Keeling%29_Islands.svg/23px-Flag_of_the_Cocos_%28Keeling%29_Islands.svg.png',
  },
  {
    name: 'Colombia',
    alphaCode2: 'CO',
    alphaCode3: 'COL',
    numericCode: '170',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/23px-Flag_of_Colombia.svg.png',
  },
  {
    name: 'Comoros',
    alphaCode2: 'KM',
    alphaCode3: 'COM',
    numericCode: '174',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/23px-Flag_of_the_Comoros.svg.png',
  },
  {
    name: 'Congo',
    alphaCode2: 'CG',
    alphaCode3: 'COG',
    numericCode: '178',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/23px-Flag_of_the_Republic_of_the_Congo.svg.png',
  },
  {
    name: 'Congo, Democratic Republic of the',
    alphaCode2: 'CD',
    alphaCode3: 'COD',
    numericCode: '180',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/20px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png',
  },
  {
    name: 'Cook Islands',
    alphaCode2: 'CK',
    alphaCode3: 'COK',
    numericCode: '184',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_the_Cook_Islands.svg/23px-Flag_of_the_Cook_Islands.svg.png',
  },
  {
    name: 'Costa Rica',
    alphaCode2: 'CR',
    alphaCode3: 'CRI',
    numericCode: '188',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/23px-Flag_of_Costa_Rica.svg.png',
  },
  {
    name: "Côte d'Ivoire",
    alphaCode2: 'CI',
    alphaCode3: 'CIV',
    numericCode: '384',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/23px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png',
  },
  {
    name: 'Croatia',
    alphaCode2: 'HR',
    alphaCode3: 'HRV',
    numericCode: '191',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/23px-Flag_of_Croatia.svg.png',
  },
  {
    name: 'Cuba',
    alphaCode2: 'CU',
    alphaCode3: 'CUB',
    numericCode: '192',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/23px-Flag_of_Cuba.svg.png',
  },
  {
    name: 'Curaçao',
    alphaCode2: 'CW',
    alphaCode3: 'CUW',
    numericCode: '531',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_Cura%C3%A7ao.svg/23px-Flag_of_Cura%C3%A7ao.svg.png',
  },
  {
    name: 'Cyprus',
    alphaCode2: 'CY',
    alphaCode3: 'CYP',
    numericCode: '196',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/23px-Flag_of_Cyprus.svg.png',
  },
  {
    name: 'Czechia',
    alphaCode2: 'CZ',
    alphaCode3: 'CZE',
    numericCode: '203',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/23px-Flag_of_the_Czech_Republic.svg.png',
  },
  {
    name: 'Denmark',
    alphaCode2: 'DK',
    alphaCode3: 'DNK',
    numericCode: '208',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/20px-Flag_of_Denmark.svg.png',
  },
  {
    name: 'Djibouti',
    alphaCode2: 'DJ',
    alphaCode3: 'DJI',
    numericCode: '262',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/23px-Flag_of_Djibouti.svg.png',
  },
  {
    name: 'Dominica',
    alphaCode2: 'DM',
    alphaCode3: 'DMA',
    numericCode: '212',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/23px-Flag_of_Dominica.svg.png',
  },
  {
    name: 'Dominican Republic',
    alphaCode2: 'DO',
    alphaCode3: 'DOM',
    numericCode: '214',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/23px-Flag_of_the_Dominican_Republic.svg.png',
  },
  {
    name: 'Ecuador',
    alphaCode2: 'EC',
    alphaCode3: 'ECU',
    numericCode: '218',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/23px-Flag_of_Ecuador.svg.png',
  },
  {
    name: 'Egypt',
    alphaCode2: 'EG',
    alphaCode3: 'EGY',
    numericCode: '818',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/23px-Flag_of_Egypt.svg.png',
  },
  {
    name: 'El Salvador',
    alphaCode2: 'SV',
    alphaCode3: 'SLV',
    numericCode: '222',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/23px-Flag_of_El_Salvador.svg.png',
  },
  {
    name: 'Equatorial Guinea',
    alphaCode2: 'GQ',
    alphaCode3: 'GNQ',
    numericCode: '226',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/23px-Flag_of_Equatorial_Guinea.svg.png',
  },
  {
    name: 'Eritrea',
    alphaCode2: 'ER',
    alphaCode3: 'ERI',
    numericCode: '232',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/23px-Flag_of_Eritrea.svg.png',
  },
  {
    name: 'Estonia',
    alphaCode2: 'EE',
    alphaCode3: 'EST',
    numericCode: '233',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/23px-Flag_of_Estonia.svg.png',
  },
  {
    name: 'Eswatini',
    alphaCode2: 'SZ',
    alphaCode3: 'SWZ',
    numericCode: '748',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Flag_of_Eswatini.svg/23px-Flag_of_Eswatini.svg.png',
  },
  {
    name: 'Ethiopia',
    alphaCode2: 'ET',
    alphaCode3: 'ETH',
    numericCode: '231',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/23px-Flag_of_Ethiopia.svg.png',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    alphaCode2: 'FK',
    alphaCode3: 'FLK',
    numericCode: '238',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/23px-Flag_of_the_Falkland_Islands.svg.png',
  },
  {
    name: 'Faroe Islands',
    alphaCode2: 'FO',
    alphaCode3: 'FRO',
    numericCode: '234',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flag_of_the_Faroe_Islands.svg/21px-Flag_of_the_Faroe_Islands.svg.png',
  },
  {
    name: 'Fiji',
    alphaCode2: 'FJ',
    alphaCode3: 'FJI',
    numericCode: '242',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/23px-Flag_of_Fiji.svg.png',
  },
  {
    name: 'Finland',
    alphaCode2: 'FI',
    alphaCode3: 'FIN',
    numericCode: '246',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/23px-Flag_of_Finland.svg.png',
  },
  {
    name: 'France',
    alphaCode2: 'FR',
    alphaCode3: 'FRA',
    numericCode: '250',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'French Guiana',
    alphaCode2: 'GF',
    alphaCode3: 'GUF',
    numericCode: '254',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'French Polynesia',
    alphaCode2: 'PF',
    alphaCode3: 'PYF',
    numericCode: '258',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/23px-Flag_of_French_Polynesia.svg.png',
  },
  {
    name: 'French Southern Territories',
    alphaCode2: 'TF',
    alphaCode3: 'ATF',
    numericCode: '260',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Flag_of_the_French_Southern_and_Antarctic_Lands.svg/23px-Flag_of_the_French_Southern_and_Antarctic_Lands.svg.png',
  },
  {
    name: 'Gabon',
    alphaCode2: 'GA',
    alphaCode3: 'GAB',
    numericCode: '266',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/20px-Flag_of_Gabon.svg.png',
  },
  {
    name: 'Gambia',
    alphaCode2: 'GM',
    alphaCode3: 'GMB',
    numericCode: '270',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/23px-Flag_of_The_Gambia.svg.png',
  },
  {
    name: 'Georgia',
    alphaCode2: 'GE',
    alphaCode3: 'GEO',
    numericCode: '268',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/23px-Flag_of_Georgia.svg.png',
  },
  {
    name: 'Germany',
    alphaCode2: 'DE',
    alphaCode3: 'DEU',
    numericCode: '276',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/23px-Flag_of_Germany.svg.png',
  },
  {
    name: 'Ghana',
    alphaCode2: 'GH',
    alphaCode3: 'GHA',
    numericCode: '288',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/23px-Flag_of_Ghana.svg.png',
  },
  {
    name: 'Gibraltar',
    alphaCode2: 'GI',
    alphaCode3: 'GIB',
    numericCode: '292',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/23px-Flag_of_Gibraltar.svg.png',
  },
  {
    name: 'Greece',
    alphaCode2: 'GR',
    alphaCode3: 'GRC',
    numericCode: '300',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/23px-Flag_of_Greece.svg.png',
  },
  {
    name: 'Greenland',
    alphaCode2: 'GL',
    alphaCode3: 'GRL',
    numericCode: '304',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_Greenland.svg/23px-Flag_of_Greenland.svg.png',
  },
  {
    name: 'Grenada',
    alphaCode2: 'GD',
    alphaCode3: 'GRD',
    numericCode: '308',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/23px-Flag_of_Grenada.svg.png',
  },
  {
    name: 'Guadeloupe',
    alphaCode2: 'GP',
    alphaCode3: 'GLP',
    numericCode: '312',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'Guam',
    alphaCode2: 'GU',
    alphaCode3: 'GUM',
    numericCode: '316',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Flag_of_Guam.svg/23px-Flag_of_Guam.svg.png',
  },
  {
    name: 'Guatemala',
    alphaCode2: 'GT',
    alphaCode3: 'GTM',
    numericCode: '320',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/23px-Flag_of_Guatemala.svg.png',
  },
  {
    name: 'Guernsey',
    alphaCode2: 'GG',
    alphaCode3: 'GGY',
    numericCode: '831',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Guernsey.svg/23px-Flag_of_Guernsey.svg.png',
  },
  {
    name: 'Guinea',
    alphaCode2: 'GN',
    alphaCode3: 'GIN',
    numericCode: '324',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/23px-Flag_of_Guinea.svg.png',
  },
  {
    name: 'Guinea-Bissau',
    alphaCode2: 'GW',
    alphaCode3: 'GNB',
    numericCode: '624',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/23px-Flag_of_Guinea-Bissau.svg.png',
  },
  {
    name: 'Guyana',
    alphaCode2: 'GY',
    alphaCode3: 'GUY',
    numericCode: '328',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/23px-Flag_of_Guyana.svg.png',
  },
  {
    name: 'Haiti',
    alphaCode2: 'HT',
    alphaCode3: 'HTI',
    numericCode: '332',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/23px-Flag_of_Haiti.svg.png',
  },
  {
    name: 'Heard Island and McDonald Islands',
    alphaCode2: 'HM',
    alphaCode3: 'HMD',
    numericCode: '334',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Flag_of_Australia.svg/23px-Flag_of_Australia.svg.png',
  },
  {
    name: 'Holy See',
    alphaCode2: 'VA',
    alphaCode3: 'VAT',
    numericCode: '336',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_the_Vatican_City.svg/16px-Flag_of_the_Vatican_City.svg.png',
  },
  {
    name: 'Honduras',
    alphaCode2: 'HN',
    alphaCode3: 'HND',
    numericCode: '340',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/23px-Flag_of_Honduras.svg.png',
  },
  {
    name: 'Hong Kong',
    alphaCode2: 'HK',
    alphaCode3: 'HKG',
    numericCode: '344',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/23px-Flag_of_Hong_Kong.svg.png',
  },
  {
    name: 'Hungary',
    alphaCode2: 'HU',
    alphaCode3: 'HUN',
    numericCode: '348',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/23px-Flag_of_Hungary.svg.png',
  },
  {
    name: 'Iceland',
    alphaCode2: 'IS',
    alphaCode3: 'ISL',
    numericCode: '352',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/21px-Flag_of_Iceland.svg.png',
  },
  {
    name: 'India',
    alphaCode2: 'IN',
    alphaCode3: 'IND',
    numericCode: '356',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
  },
  {
    name: 'Indonesia',
    alphaCode2: 'ID',
    alphaCode3: 'IDN',
    numericCode: '360',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/23px-Flag_of_Indonesia.svg.png',
  },
  {
    name: 'Iran (Islamic Republic of)',
    alphaCode2: 'IR',
    alphaCode3: 'IRN',
    numericCode: '364',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/23px-Flag_of_Iran.svg.png',
  },
  {
    name: 'Iraq',
    alphaCode2: 'IQ',
    alphaCode3: 'IRQ',
    numericCode: '368',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/23px-Flag_of_Iraq.svg.png',
  },
  {
    name: 'Ireland',
    alphaCode2: 'IE',
    alphaCode3: 'IRL',
    numericCode: '372',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/23px-Flag_of_Ireland.svg.png',
  },
  {
    name: 'Isle of Man',
    alphaCode2: 'IM',
    alphaCode3: 'IMN',
    numericCode: '833',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_the_Isle_of_Man.svg/23px-Flag_of_the_Isle_of_Man.svg.png',
  },
  {
    name: 'Israel',
    alphaCode2: 'IL',
    alphaCode3: 'ISR',
    numericCode: '376',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/21px-Flag_of_Israel.svg.png',
  },
  {
    name: 'Italy',
    alphaCode2: 'IT',
    alphaCode3: 'ITA',
    numericCode: '380',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Flag_of_Italy.svg/23px-Flag_of_Italy.svg.png',
  },
  {
    name: 'Jamaica',
    alphaCode2: 'JM',
    alphaCode3: 'JAM',
    numericCode: '388',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/23px-Flag_of_Jamaica.svg.png',
  },
  {
    name: 'Japan',
    alphaCode2: 'JP',
    alphaCode3: 'JPN',
    numericCode: '392',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Flag_of_Japan.svg/23px-Flag_of_Japan.svg.png',
  },
  {
    name: 'Jersey',
    alphaCode2: 'JE',
    alphaCode3: 'JEY',
    numericCode: '832',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Flag_of_Jersey.svg/23px-Flag_of_Jersey.svg.png',
  },
  {
    name: 'Jordan',
    alphaCode2: 'JO',
    alphaCode3: 'JOR',
    numericCode: '400',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/23px-Flag_of_Jordan.svg.png',
  },
  {
    name: 'Kazakhstan',
    alphaCode2: 'KZ',
    alphaCode3: 'KAZ',
    numericCode: '398',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/23px-Flag_of_Kazakhstan.svg.png',
  },
  {
    name: 'Kenya',
    alphaCode2: 'KE',
    alphaCode3: 'KEN',
    numericCode: '404',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/23px-Flag_of_Kenya.svg.png',
  },
  {
    name: 'Kiribati',
    alphaCode2: 'KI',
    alphaCode3: 'KIR',
    numericCode: '296',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/23px-Flag_of_Kiribati.svg.png',
  },
  {
    name: "Korea (Democratic People's Republic of)",
    alphaCode2: 'KP',
    alphaCode3: 'PRK',
    numericCode: '408',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/23px-Flag_of_North_Korea.svg.png',
  },
  {
    name: 'Korea, Republic of',
    alphaCode2: 'KR',
    alphaCode3: 'KOR',
    numericCode: '410',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/23px-Flag_of_South_Korea.svg.png',
  },
  {
    name: 'Kuwait',
    alphaCode2: 'KW',
    alphaCode3: 'KWT',
    numericCode: '414',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/23px-Flag_of_Kuwait.svg.png',
  },
  {
    name: 'Kyrgyzstan',
    alphaCode2: 'KG',
    alphaCode3: 'KGZ',
    numericCode: '417',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/23px-Flag_of_Kyrgyzstan.svg.png',
  },
  {
    name: "Lao People's Democratic Republic",
    alphaCode2: 'LA',
    alphaCode3: 'LAO',
    numericCode: '418',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/23px-Flag_of_Laos.svg.png',
  },
  {
    name: 'Latvia',
    alphaCode2: 'LV',
    alphaCode3: 'LVA',
    numericCode: '428',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/23px-Flag_of_Latvia.svg.png',
  },
  {
    name: 'Lebanon',
    alphaCode2: 'LB',
    alphaCode3: 'LBN',
    numericCode: '422',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/23px-Flag_of_Lebanon.svg.png',
  },
  {
    name: 'Lesotho',
    alphaCode2: 'LS',
    alphaCode3: 'LSO',
    numericCode: '426',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/23px-Flag_of_Lesotho.svg.png',
  },
  {
    name: 'Liberia',
    alphaCode2: 'LR',
    alphaCode3: 'LBR',
    numericCode: '430',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/23px-Flag_of_Liberia.svg.png',
  },
  {
    name: 'Libya',
    alphaCode2: 'LY',
    alphaCode3: 'LBY',
    numericCode: '434',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/23px-Flag_of_Libya.svg.png',
  },
  {
    name: 'Liechtenstein',
    alphaCode2: 'LI',
    alphaCode3: 'LIE',
    numericCode: '438',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/23px-Flag_of_Liechtenstein.svg.png',
  },
  {
    name: 'Lithuania',
    alphaCode2: 'LT',
    alphaCode3: 'LTU',
    numericCode: '440',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/23px-Flag_of_Lithuania.svg.png',
  },
  {
    name: 'Luxembourg',
    alphaCode2: 'LU',
    alphaCode3: 'LUX',
    numericCode: '442',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/23px-Flag_of_Luxembourg.svg.png',
  },
  {
    name: 'Macao',
    alphaCode2: 'MO',
    alphaCode3: 'MAC',
    numericCode: '446',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/23px-Flag_of_Macau.svg.png',
  },
  {
    name: 'Madagascar',
    alphaCode2: 'MG',
    alphaCode3: 'MDG',
    numericCode: '450',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/23px-Flag_of_Madagascar.svg.png',
  },
  {
    name: 'Malawi',
    alphaCode2: 'MW',
    alphaCode3: 'MWI',
    numericCode: '454',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/23px-Flag_of_Malawi.svg.png',
  },
  {
    name: 'Malaysia',
    alphaCode2: 'MY',
    alphaCode3: 'MYS',
    numericCode: '458',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/23px-Flag_of_Malaysia.svg.png',
  },
  {
    name: 'Maldives',
    alphaCode2: 'MV',
    alphaCode3: 'MDV',
    numericCode: '462',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/23px-Flag_of_Maldives.svg.png',
  },
  {
    name: 'Mali',
    alphaCode2: 'ML',
    alphaCode3: 'MLI',
    numericCode: '466',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/23px-Flag_of_Mali.svg.png',
  },
  {
    name: 'Malta',
    alphaCode2: 'MT',
    alphaCode3: 'MLT',
    numericCode: '470',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/23px-Flag_of_Malta.svg.png',
  },
  {
    name: 'Marshall Islands',
    alphaCode2: 'MH',
    alphaCode3: 'MHL',
    numericCode: '584',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/23px-Flag_of_the_Marshall_Islands.svg.png',
  },
  {
    name: 'Martinique',
    alphaCode2: 'MQ',
    alphaCode3: 'MTQ',
    numericCode: '474',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'Mauritania',
    alphaCode2: 'MR',
    alphaCode3: 'MRT',
    numericCode: '478',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/23px-Flag_of_Mauritania.svg.png',
  },
  {
    name: 'Mauritius',
    alphaCode2: 'MU',
    alphaCode3: 'MUS',
    numericCode: '480',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/23px-Flag_of_Mauritius.svg.png',
  },
  {
    name: 'Mayotte',
    alphaCode2: 'YT',
    alphaCode3: 'MYT',
    numericCode: '175',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'Mexico',
    alphaCode2: 'MX',
    alphaCode3: 'MEX',
    numericCode: '484',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/23px-Flag_of_Mexico.svg.png',
  },
  {
    name: 'Micronesia (Federated States of)',
    alphaCode2: 'FM',
    alphaCode3: 'FSM',
    numericCode: '583',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg/23px-Flag_of_the_Federated_States_of_Micronesia.svg.png',
  },
  {
    name: 'Moldova, Republic of',
    alphaCode2: 'MD',
    alphaCode3: 'MDA',
    numericCode: '498',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/23px-Flag_of_Moldova.svg.png',
  },
  {
    name: 'Monaco',
    alphaCode2: 'MC',
    alphaCode3: 'MCO',
    numericCode: '492',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/19px-Flag_of_Monaco.svg.png',
  },
  {
    name: 'Mongolia',
    alphaCode2: 'MN',
    alphaCode3: 'MNG',
    numericCode: '496',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/23px-Flag_of_Mongolia.svg.png',
  },
  {
    name: 'Montenegro',
    alphaCode2: 'ME',
    alphaCode3: 'MNE',
    numericCode: '499',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/23px-Flag_of_Montenegro.svg.png',
  },
  {
    name: 'Montserrat',
    alphaCode2: 'MS',
    alphaCode3: 'MSR',
    numericCode: '500',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Montserrat.svg/23px-Flag_of_Montserrat.svg.png',
  },
  {
    name: 'Morocco',
    alphaCode2: 'MA',
    alphaCode3: 'MAR',
    numericCode: '504',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/23px-Flag_of_Morocco.svg.png',
  },
  {
    name: 'Mozambique',
    alphaCode2: 'MZ',
    alphaCode3: 'MOZ',
    numericCode: '508',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/23px-Flag_of_Mozambique.svg.png',
  },
  {
    name: 'Myanmar',
    alphaCode2: 'MM',
    alphaCode3: 'MMR',
    numericCode: '104',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/23px-Flag_of_Myanmar.svg.png',
  },
  {
    name: 'Namibia',
    alphaCode2: 'NA',
    alphaCode3: 'NAM',
    numericCode: '516',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/23px-Flag_of_Namibia.svg.png',
  },
  {
    name: 'Nauru',
    alphaCode2: 'NR',
    alphaCode3: 'NRU',
    numericCode: '520',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/23px-Flag_of_Nauru.svg.png',
  },
  {
    name: 'Nepal',
    alphaCode2: 'NP',
    alphaCode3: 'NPL',
    numericCode: '524',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/16px-Flag_of_Nepal.svg.png',
  },
  {
    name: 'Netherlands',
    alphaCode2: 'NL',
    alphaCode3: 'NLD',
    numericCode: '528',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/23px-Flag_of_the_Netherlands.svg.png',
  },
  {
    name: 'New Caledonia',
    alphaCode2: 'NC',
    alphaCode3: 'NCL',
    numericCode: '540',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flags_of_New_Caledonia.svg/43px-Flags_of_New_Caledonia.svg.png',
  },
  {
    name: 'New Zealand',
    alphaCode2: 'NZ',
    alphaCode3: 'NZL',
    numericCode: '554',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/23px-Flag_of_New_Zealand.svg.png',
  },
  {
    name: 'Nicaragua',
    alphaCode2: 'NI',
    alphaCode3: 'NIC',
    numericCode: '558',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/23px-Flag_of_Nicaragua.svg.png',
  },
  {
    name: 'Niger',
    alphaCode2: 'NE',
    alphaCode3: 'NER',
    numericCode: '562',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/18px-Flag_of_Niger.svg.png',
  },
  {
    name: 'Nigeria',
    alphaCode2: 'NG',
    alphaCode3: 'NGA',
    numericCode: '566',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/23px-Flag_of_Nigeria.svg.png',
  },
  {
    name: 'Niue',
    alphaCode2: 'NU',
    alphaCode3: 'NIU',
    numericCode: '570',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Niue.svg/23px-Flag_of_Niue.svg.png',
  },
  {
    name: 'Norfolk Island',
    alphaCode2: 'NF',
    alphaCode3: 'NFK',
    numericCode: '574',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Norfolk_Island.svg/23px-Flag_of_Norfolk_Island.svg.png',
  },
  {
    name: 'North Macedonia',
    alphaCode2: 'MK',
    alphaCode3: 'MKD',
    numericCode: '807',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_North_Macedonia.svg/23px-Flag_of_North_Macedonia.svg.png',
  },
  {
    name: 'Northern Mariana Islands',
    alphaCode2: 'MP',
    alphaCode3: 'MNP',
    numericCode: '580',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Flag_of_the_Northern_Mariana_Islands.svg/23px-Flag_of_the_Northern_Mariana_Islands.svg.png',
  },
  {
    name: 'Norway',
    alphaCode2: 'NO',
    alphaCode3: 'NOR',
    numericCode: '578',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/21px-Flag_of_Norway.svg.png',
  },
  {
    name: 'Oman',
    alphaCode2: 'OM',
    alphaCode3: 'OMN',
    numericCode: '512',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/23px-Flag_of_Oman.svg.png',
  },
  {
    name: 'Pakistan',
    alphaCode2: 'PK',
    alphaCode3: 'PAK',
    numericCode: '586',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/23px-Flag_of_Pakistan.svg.png',
  },
  {
    name: 'Palau',
    alphaCode2: 'PW',
    alphaCode3: 'PLW',
    numericCode: '585',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/23px-Flag_of_Palau.svg.png',
  },
  {
    name: 'Palestine, State of',
    alphaCode2: 'PS',
    alphaCode3: 'PSE',
    numericCode: '275',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Palestine.svg/23px-Flag_of_Palestine.svg.png',
  },
  {
    name: 'Panama',
    alphaCode2: 'PA',
    alphaCode3: 'PAN',
    numericCode: '591',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/23px-Flag_of_Panama.svg.png',
  },
  {
    name: 'Papua New Guinea',
    alphaCode2: 'PG',
    alphaCode3: 'PNG',
    numericCode: '598',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/20px-Flag_of_Papua_New_Guinea.svg.png',
  },
  {
    name: 'Paraguay',
    alphaCode2: 'PY',
    alphaCode3: 'PRY',
    numericCode: '600',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/23px-Flag_of_Paraguay.svg.png',
  },
  {
    name: 'Peru',
    alphaCode2: 'PE',
    alphaCode3: 'PER',
    numericCode: '604',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/23px-Flag_of_Peru.svg.png',
  },
  {
    name: 'Philippines',
    alphaCode2: 'PH',
    alphaCode3: 'PHL',
    numericCode: '608',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/23px-Flag_of_the_Philippines.svg.png',
  },
  {
    name: 'Pitcairn',
    alphaCode2: 'PN',
    alphaCode3: 'PCN',
    numericCode: '612',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_the_Pitcairn_Islands.svg/23px-Flag_of_the_Pitcairn_Islands.svg.png',
  },
  {
    name: 'Poland',
    alphaCode2: 'PL',
    alphaCode3: 'POL',
    numericCode: '616',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Flag_of_Poland.svg/23px-Flag_of_Poland.svg.png',
  },
  {
    name: 'Portugal',
    alphaCode2: 'PT',
    alphaCode3: 'PRT',
    numericCode: '620',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/23px-Flag_of_Portugal.svg.png',
  },
  {
    name: 'Puerto Rico',
    alphaCode2: 'PR',
    alphaCode3: 'PRI',
    numericCode: '630',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Flag_of_Puerto_Rico.svg/23px-Flag_of_Puerto_Rico.svg.png',
  },
  {
    name: 'Qatar',
    alphaCode2: 'QA',
    alphaCode3: 'QAT',
    numericCode: '634',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/23px-Flag_of_Qatar.svg.png',
  },
  {
    name: 'Réunion',
    alphaCode2: 'RE',
    alphaCode3: 'REU',
    numericCode: '638',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'Romania',
    alphaCode2: 'RO',
    alphaCode3: 'ROU',
    numericCode: '642',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/23px-Flag_of_Romania.svg.png',
  },
  {
    name: 'Russian Federation',
    alphaCode2: 'RU',
    alphaCode3: 'RUS',
    numericCode: '643',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/23px-Flag_of_Russia.svg.png',
  },
  {
    name: 'Rwanda',
    alphaCode2: 'RW',
    alphaCode3: 'RWA',
    numericCode: '646',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/23px-Flag_of_Rwanda.svg.png',
  },
  {
    name: 'Saint Barthélemy',
    alphaCode2: 'BL',
    alphaCode3: 'BLM',
    numericCode: '652',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    alphaCode2: 'SH',
    alphaCode3: 'SHN',
    numericCode: '654',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png',
  },
  {
    name: 'Saint Kitts and Nevis',
    alphaCode2: 'KN',
    alphaCode3: 'KNA',
    numericCode: '659',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/23px-Flag_of_Saint_Kitts_and_Nevis.svg.png',
  },
  {
    name: 'Saint Lucia',
    alphaCode2: 'LC',
    alphaCode3: 'LCA',
    numericCode: '662',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/23px-Flag_of_Saint_Lucia.svg.png',
  },
  {
    name: 'Saint Martin (French part)',
    alphaCode2: 'MF',
    alphaCode3: 'MAF',
    numericCode: '663',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'Saint Pierre and Miquelon',
    alphaCode2: 'PM',
    alphaCode3: 'SPM',
    numericCode: '666',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    alphaCode2: 'VC',
    alphaCode3: 'VCT',
    numericCode: '670',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/23px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png',
  },
  {
    name: 'Samoa',
    alphaCode2: 'WS',
    alphaCode3: 'WSM',
    numericCode: '882',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/23px-Flag_of_Samoa.svg.png',
  },
  {
    name: 'San Marino',
    alphaCode2: 'SM',
    alphaCode3: 'SMR',
    numericCode: '674',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/20px-Flag_of_San_Marino.svg.png',
  },
  {
    name: 'Sao Tome and Principe',
    alphaCode2: 'ST',
    alphaCode3: 'STP',
    numericCode: '678',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Sao_Tome_and_Principe.svg/23px-Flag_of_Sao_Tome_and_Principe.svg.png',
  },
  {
    name: 'Saudi Arabia',
    alphaCode2: 'SA',
    alphaCode3: 'SAU',
    numericCode: '682',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/23px-Flag_of_Saudi_Arabia.svg.png',
  },
  {
    name: 'Senegal',
    alphaCode2: 'SN',
    alphaCode3: 'SEN',
    numericCode: '686',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/23px-Flag_of_Senegal.svg.png',
  },
  {
    name: 'Serbia',
    alphaCode2: 'RS',
    alphaCode3: 'SRB',
    numericCode: '688',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/23px-Flag_of_Serbia.svg.png',
  },
  {
    name: 'Seychelles',
    alphaCode2: 'SC',
    alphaCode3: 'SYC',
    numericCode: '690',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/23px-Flag_of_Seychelles.svg.png',
  },
  {
    name: 'Sierra Leone',
    alphaCode2: 'SL',
    alphaCode3: 'SLE',
    numericCode: '694',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/23px-Flag_of_Sierra_Leone.svg.png',
  },
  {
    name: 'Singapore',
    alphaCode2: 'SG',
    alphaCode3: 'SGP',
    numericCode: '702',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/23px-Flag_of_Singapore.svg.png',
  },
  {
    name: 'Sint Maarten (Dutch part)',
    alphaCode2: 'SX',
    alphaCode3: 'SXM',
    numericCode: '534',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Sint_Maarten.svg/23px-Flag_of_Sint_Maarten.svg.png',
  },
  {
    name: 'Slovakia',
    alphaCode2: 'SK',
    alphaCode3: 'SVK',
    numericCode: '703',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/23px-Flag_of_Slovakia.svg.png',
  },
  {
    name: 'Slovenia',
    alphaCode2: 'SI',
    alphaCode3: 'SVN',
    numericCode: '705',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/23px-Flag_of_Slovenia.svg.png',
  },
  {
    name: 'Solomon Islands',
    alphaCode2: 'SB',
    alphaCode3: 'SLB',
    numericCode: '090',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/23px-Flag_of_the_Solomon_Islands.svg.png',
  },
  {
    name: 'Somalia',
    alphaCode2: 'SO',
    alphaCode3: 'SOM',
    numericCode: '706',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/23px-Flag_of_Somalia.svg.png',
  },
  {
    name: 'South Africa',
    alphaCode2: 'ZA',
    alphaCode3: 'ZAF',
    numericCode: '710',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/23px-Flag_of_South_Africa.svg.png',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    alphaCode2: 'GS',
    alphaCode3: 'SGS',
    numericCode: '239',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg/23px-Flag_of_South_Georgia_and_the_South_Sandwich_Islands.svg.png',
  },
  {
    name: 'South Sudan',
    alphaCode2: 'SS',
    alphaCode3: 'SSD',
    numericCode: '728',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/23px-Flag_of_South_Sudan.svg.png',
  },
  {
    name: 'Spain',
    alphaCode2: 'ES',
    alphaCode3: 'ESP',
    numericCode: '724',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Flag_of_Spain.svg/23px-Flag_of_Spain.svg.png',
  },
  {
    name: 'Sri Lanka',
    alphaCode2: 'LK',
    alphaCode3: 'LKA',
    numericCode: '144',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/23px-Flag_of_Sri_Lanka.svg.png',
  },
  {
    name: 'Sudan',
    alphaCode2: 'SD',
    alphaCode3: 'SDN',
    numericCode: '729',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/23px-Flag_of_Sudan.svg.png',
  },
  {
    name: 'Suriname',
    alphaCode2: 'SR',
    alphaCode3: 'SUR',
    numericCode: '740',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/23px-Flag_of_Suriname.svg.png',
  },
  {
    name: 'Svalbard and Jan Mayen',
    alphaCode2: 'SJ',
    alphaCode3: 'SJM',
    numericCode: '744',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/21px-Flag_of_Norway.svg.png',
  },
  {
    name: 'Sweden',
    alphaCode2: 'SE',
    alphaCode3: 'SWE',
    numericCode: '752',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/Flag_of_Sweden.svg/23px-Flag_of_Sweden.svg.png',
  },
  {
    name: 'Switzerland',
    alphaCode2: 'CH',
    alphaCode3: 'CHE',
    numericCode: '756',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/16px-Flag_of_Switzerland.svg.png',
  },
  {
    name: 'Syrian Arab Republic',
    alphaCode2: 'SY',
    alphaCode3: 'SYR',
    numericCode: '760',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/23px-Flag_of_Syria.svg.png',
  },
  {
    name: 'Taiwan, Province of China',
    alphaCode2: 'TW',
    alphaCode3: 'TWN',
    numericCode: '158',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/23px-Flag_of_the_Republic_of_China.svg.png',
  },
  {
    name: 'Tajikistan',
    alphaCode2: 'TJ',
    alphaCode3: 'TJK',
    numericCode: '762',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/23px-Flag_of_Tajikistan.svg.png',
  },
  {
    name: 'Tanzania, United Republic of',
    alphaCode2: 'TZ',
    alphaCode3: 'TZA',
    numericCode: '834',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/23px-Flag_of_Tanzania.svg.png',
  },
  {
    name: 'Thailand',
    alphaCode2: 'TH',
    alphaCode3: 'THA',
    numericCode: '764',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/23px-Flag_of_Thailand.svg.png',
  },
  {
    name: 'Timor-Leste',
    alphaCode2: 'TL',
    alphaCode3: 'TLS',
    numericCode: '626',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/23px-Flag_of_East_Timor.svg.png',
  },
  {
    name: 'Togo',
    alphaCode2: 'TG',
    alphaCode3: 'TGO',
    numericCode: '768',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/23px-Flag_of_Togo.svg.png',
  },
  {
    name: 'Tokelau',
    alphaCode2: 'TK',
    alphaCode3: 'TKL',
    numericCode: '772',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Flag_of_Tokelau.svg/23px-Flag_of_Tokelau.svg.png',
  },
  {
    name: 'Tonga',
    alphaCode2: 'TO',
    alphaCode3: 'TON',
    numericCode: '776',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/23px-Flag_of_Tonga.svg.png',
  },
  {
    name: 'Trinidad and Tobago',
    alphaCode2: 'TT',
    alphaCode3: 'TTO',
    numericCode: '780',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/23px-Flag_of_Trinidad_and_Tobago.svg.png',
  },
  {
    name: 'Tunisia',
    alphaCode2: 'TN',
    alphaCode3: 'TUN',
    numericCode: '788',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/23px-Flag_of_Tunisia.svg.png',
  },
  {
    name: 'Turkey',
    alphaCode2: 'TR',
    alphaCode3: 'TUR',
    numericCode: '792',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/23px-Flag_of_Turkey.svg.png',
  },
  {
    name: 'Turkmenistan',
    alphaCode2: 'TM',
    alphaCode3: 'TKM',
    numericCode: '795',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/23px-Flag_of_Turkmenistan.svg.png',
  },
  {
    name: 'Turks and Caicos Islands',
    alphaCode2: 'TC',
    alphaCode3: 'TCA',
    numericCode: '796',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg/23px-Flag_of_the_Turks_and_Caicos_Islands.svg.png',
  },
  {
    name: 'Tuvalu',
    alphaCode2: 'TV',
    alphaCode3: 'TUV',
    numericCode: '798',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/23px-Flag_of_Tuvalu.svg.png',
  },
  {
    name: 'Uganda',
    alphaCode2: 'UG',
    alphaCode3: 'UGA',
    numericCode: '800',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/23px-Flag_of_Uganda.svg.png',
  },
  {
    name: 'Ukraine',
    alphaCode2: 'UA',
    alphaCode3: 'UKR',
    numericCode: '804',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/23px-Flag_of_Ukraine.svg.png',
  },
  {
    name: 'United Arab Emirates',
    alphaCode2: 'AE',
    alphaCode3: 'ARE',
    numericCode: '784',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/23px-Flag_of_the_United_Arab_Emirates.svg.png',
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    alphaCode2: 'GB',
    alphaCode3: 'GBR',
    numericCode: '826',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/ae/Flag_of_the_United_Kingdom.svg/23px-Flag_of_the_United_Kingdom.svg.png',
  },
  {
    name: 'United States of America',
    alphaCode2: 'US',
    alphaCode3: 'USA',
    numericCode: '840',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png',
  },
  {
    name: 'United States Minor Outlying Islands',
    alphaCode2: 'UM',
    alphaCode3: 'UMI',
    numericCode: '581',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png',
  },
  {
    name: 'Uruguay',
    alphaCode2: 'UY',
    alphaCode3: 'URY',
    numericCode: '858',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/23px-Flag_of_Uruguay.svg.png',
  },
  {
    name: 'Uzbekistan',
    alphaCode2: 'UZ',
    alphaCode3: 'UZB',
    numericCode: '860',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/23px-Flag_of_Uzbekistan.svg.png',
  },
  {
    name: 'Vanuatu',
    alphaCode2: 'VU',
    alphaCode3: 'VUT',
    numericCode: '548',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/23px-Flag_of_Vanuatu.svg.png',
  },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    alphaCode2: 'VE',
    alphaCode3: 'VEN',
    numericCode: '862',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/23px-Flag_of_Venezuela.svg.png',
  },
  {
    name: 'Viet Nam',
    alphaCode2: 'VN',
    alphaCode3: 'VNM',
    numericCode: '704',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/23px-Flag_of_Vietnam.svg.png',
  },
  {
    name: 'Virgin Islands (British)',
    alphaCode2: 'VG',
    alphaCode3: 'VGB',
    numericCode: '092',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Flag_of_the_British_Virgin_Islands.svg/23px-Flag_of_the_British_Virgin_Islands.svg.png',
  },
  {
    name: 'Virgin Islands (U.S.)',
    alphaCode2: 'VI',
    alphaCode3: 'VIR',
    numericCode: '850',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_the_United_States_Virgin_Islands.svg/23px-Flag_of_the_United_States_Virgin_Islands.svg.png',
  },
  {
    name: 'Wallis and Futuna',
    alphaCode2: 'WF',
    alphaCode3: 'WLF',
    numericCode: '876',
    flagLink: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/Flag_of_France.svg/23px-Flag_of_France.svg.png',
  },
  {
    name: 'Western Sahara',
    alphaCode2: 'EH',
    alphaCode3: 'ESH',
    numericCode: '732',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg/23px-Flag_of_the_Sahrawi_Arab_Democratic_Republic.svg.png',
  },
  {
    name: 'Yemen',
    alphaCode2: 'YE',
    alphaCode3: 'YEM',
    numericCode: '887',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/23px-Flag_of_Yemen.svg.png',
  },
  {
    name: 'Zambia',
    alphaCode2: 'ZM',
    alphaCode3: 'ZMB',
    numericCode: '894',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/23px-Flag_of_Zambia.svg.png',
  },
  {
    name: 'Zimbabwe',
    alphaCode2: 'ZW',
    alphaCode3: 'ZWE',
    numericCode: '716',
    flagLink: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/23px-Flag_of_Zimbabwe.svg.png',
  },
];
