service: juriscloud
app: juriscloud
org: rodrigogs

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-finch
  - serverless-pseudo-parameters

package:
  individually: true

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
  client:
    bucketName: '${self:service}-${self:provider.stage}-webapp'
    distributionFolder: 'frontend/dist'
  usersTableName: '${self:service}-${self:provider.stage}-users'

provider:
  name: aws
  profile: rodrigogs
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: sa-east-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'logs:*'
      Resource: '*'
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource:
        Fn::GetAtt:
          - UsersTable
          - Arn
  environment:
    USERS_TABLE: ${self:custom.usersTableName}

functions:
  authorizer:
    handler: backend/functions/authorizer/index.handler

  healthcheck:
    handler: backend/functions/api/healthcheck.handler
    events:
      - http:
          method: get
          path: /
          cors: true

  fail:
    handler: backend/functions/api/fail.handler
    events:
      - http:
          method: get
          path: /fail/{status}/{message}
          cors: true
          authorizer: authorizer

  enquire:
    handler: backend/functions/api/enquire.handler
    events:
      - http:
          method: post
          path: /enquire
          cors: true
          authorizer: authorizer

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    # Dynamo Tables
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
