module.exports = {
  initialize: 'initialize',
  reconnaissance: {
    basicInfo: {
      questionFullName: 'question_full_name',
      questionNickName: 'question_nick_name',
      questionNationality: 'question_nationality',
      questionCivilStatus: 'question_civil_status',
      questionProfession: 'question_profession',
      questionRg: 'question_rg',
      questionCpf: 'question_cpf',
      questionAddressCep: 'question_address_cep',
      questionAddressState: 'question_address_state',
      questionAddressCity: 'question_address_city',
      questionAddressNeighborhood: 'question_address_neighborhood',
      questionAddressStreet: 'question_address_street',
      questionAddressNumber: 'question_address_number',
      questionAddressComplement: 'question_address_complement',
      questionMotherName: 'question_mother_name',
      questionFatherName: 'question_father_name',
      questionPhones: 'question_phones',
      questionEmails: 'question_emails',
      questionNit: 'question_nit',
      questionMyInssPassword: 'question_my_inss_password',
    },
  },
};
